### ISSUE TITLE
How do I run this without a webcam?

### ISSUE THREAD

**Issue by InfiniteCoder01** [mkuf/prind#103]
If I just comment services section out in docker-compose.override.yaml, some weird errors pop up... Might be not because of webcam, but to be sure, what is the intended way?

**Comment by mkuf** [comment]
Hi there, 

if you do not wish to override any other service, you can simply remove the override file all together.  

If you wish to keep the file just in case and only want to remove the webcam service, you'll have to set `services` to an empty map like so: 

````yaml
## Ustreamer base Service
x-ustreamer-svc: &ustreamer-svc
  image: mkuf/ustreamer:latest
  restart: unless-stopped
  command: --host=0.0.0.0 --port=8080 --slowdown --device=/dev/webcam --resolution=1280x960 --format=MJPEG --desired-fps=30

## Add your personal config here
services: {}
````

-Markus
