### ISSUE TITLE
Broken webcam config

### ISSUE THREAD

**Issue by flynny75** [mkuf/prind#17]
Fluidd & Mainsail can not serve the ustreamer stream in the provided configuration. Mainsail & Fluidd are reaching out to '/webcam', but the traefik path prefix is '/stream'.

Changing the path prefix to '/webcam' is not enough, as the '/webcam' path reaches ustreamer, which doesn't know what to do with it. Changing the default ustreamer service config to:

```
  ustreamer:
    <<: *ustreamer-svc
    container_name: ustreamer
    devices:
      - /dev/video0:/dev/webcam
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.webcam.loadbalancer.server.port=8080"
      - "traefik.http.routers.webcam.rule=PathPrefix(`/webcam`)"
      - "traefik.http.routers.webcam.entrypoints=web"
      - "traefik.http.middlewares.webcam.stripprefix.prefixes=/webcam"
      - "traefik.http.routers.webcam.middlewares=webcam"
```

fixes the issue, and Mainsail & Fluidd can serve the first webcam. I can submit a PR for this if required.
