### ISSUE TITLE
Expose Moonraker Port for use with GetHomepage

### ISSUE THREAD

**Issue by mircsicz** [mkuf/prind#196]
I've always had Octoprint integrated into my 'Homepage'

Now that I klipperized my Kobra2Neo and migrated to Mainsail I wanted to change to the Moonraker [widget](https://gethomepage.dev/widgets/services/moonraker/) 

```
    - Klipper:
          href: http://10.10.xxx.19
          widget:
            type: moonraker
            url: http://10.10.xxx.19:7125
            fields: ["printer_state","print_status","print_progress","layers"]
```
so I've tried to adjust in docker-compose.yaml:

```
  ## WebApi
  ##
  moonraker:
    image: mkuf/moonraker:latest
    restart: unless-stopped
    pid: host
    logging:
      driver: none
    #ports:
    #  - "7125:7125"
```
But with the 'ports:' statement being uncommented I can't reach the port...

I don't have any experience using labels, so I hope you can give me hint what I need to adjust instead of 'ports'.
