### ISSUE TITLE
Can host reboot/shutdown from mainsail be enabled?

### ISSUE THREAD

**Issue by HitLuca** [mkuf/prind#53]
I was wondering, since I've deployed this project to a raspberry pi, would it be possible to have the reboot/shutdown commands working from moonraker? I get an error when I try to do it:
```
Traceback (most recent call last):

  File "/opt/moonraker/moonraker/websockets.py", line 299, in execute_method
    result = await callback(params)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/moonraker/moonraker/websockets.py", line 412, in func
    result = await callback(
             ^^^^^^^^^^^^^^^
  File "/opt/moonraker/moonraker/components/machine.py", line 277, in _handle_machine_request
    raise self.server.error(
utils.ServerError: Cannot reboot from within a docker container
```

I saw that a method to do this is to mount `/etc/systemd` in the container, but it's already done

**Comment by mkuf** [comment]
This is certainly possible and should work out of the box, as `/run/systemd` and `/run/dbus` are mounted within the container.
I just tested this with the most recent moonraker image (`61d3182`) and could not reproduce the described behaviour.

Please run the get-info script, upload the generated archive and provide the **command you used to start the stack**.
```bash
cd prind
bash ./scripts/get-info.sh
```

-Markus

**Comment by HitLuca** [comment]
Very strange, it may be related to my setup. I'm using portainer/ubuntu server/raspberry pi 3b+

**Comment by HitLuca** [comment]
@mkuf here is my portainer compose, as well as the output of `get-info.sh` ran from my prind config folder

```
services:
  klipper:
    image: mkuf/klipper:latest
    restart: unless-stopped
    command: -I printer_data/run/klipper.tty -a printer_data/run/klipper.sock printer_data/config/printer.cfg -l printer_data/logs/klippy.log
    devices:
      - /dev/serial/by-id/usb-Klipper_stm32f401xc_160035000751383531393138-if00:/dev/serial/by-id/usb-Klipper_stm32f401xc_160035000751383531393138-if00
    volumes:
      - /home/pi/docker/prind/config:/opt/printer_data/config
      - /home/pi/docker/prind/run:/opt/printer_data/run
      - /home/pi/docker/prind/gcode:/opt/printer_data/gcodes
      - /home/pi/docker/prind/log:/opt/printer_data/logs
    labels:
      org.prind.service: klipper
      org.prind.printer: voron-0
      com.centurylinklabs.watchtower.enable: false
      
  moonraker:
    image: mkuf/moonraker:latest
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - /dev/null:/opt/klipper/config/null
      - /dev/null:/opt/klipper/docs/null
      - /run/dbus:/run/dbus
      - /run/systemd:/run/systemd
      - /home/pi/docker/prind/run:/opt/printer_data/run
      - /home/pi/docker/prind/gcode:/opt/printer_data/gcodes
      - /home/pi/docker/prind/log:/opt/printer_data/logs
      - /home/pi/docker/prind/moonraker-db:/opt/printer_data/database
      - /home/pi/docker/prind/config:/opt/printer_data/config
    labels:
      org.prind.service: moonraker
      org.prind.printer: voron-0
      com.centurylinklabs.watchtower.enable: false
      
  mainsail:
    image: ghcr.io/mainsail-crew/mainsail:edge
    restart: unless-stopped
    network_mode: host
    volumes:
      - /home/pi/docker/prind/mainsail-config.json:/usr/share/nginx/html/config.json
    labels:
      org.prind.service: mainsail
```
[prind-info-02022023-192510.tar.gz](https://github.com/mkuf/prind/files/10572193/prind-info-02022023-192510.tar.gz)
