### ISSUE TITLE
How to add Python script file to the Klipper container klipper/extras folder?

### ISSUE THREAD

**Issue by GAZ082** [mkuf/prind#76]
Hi. I'd like to install the gcode to shell script. How can I add it to the klippy/extras folder inside the container?

Thanks.

**Comment by mkuf** [comment]
You can add files to the container via volumes, just like with all the other files that get mounted into the Containers. 

This can be achieved via `docker-compose.override.yaml`, but be sure to include all volumes that are defined for the klipper service in `docker-compose.yaml`. You may then add a new volume at the end of the volumes list as shown below: 

```yaml
services:
  klipper:
    volumes:
      - ./config:/opt/printer_data/config
      - run:/opt/printer_data/run
      - gcode:/opt/printer_data/gcodes
      - log:/opt/printer_data/logs
      - /path/to/my/custom/plugins:/opt/klipper/klippy/extras
```

**Comment by GAZ082** [comment]
This is my whole klipper block in the override file:

```
services:
  klipper:
    privileged: true
    volumes:
      - ./config:/opt/printer_data/config
      - run:/opt/printer_data/run
      - gcode:/opt/printer_data/gcodes
      - log:/opt/printer_data/logs
      - /home/alarm/prind/custom/plugins:/opt/klipper/klippy/extras
    devices:
      - dev/serial/by-id/usb-1a86_USB_Serial-if00-port0:dev/ttyUSB0
```
If i add the plugins folder I get the error:

`Unable to load module : stepper_enable`

The plugins folder in my host is empty BTW. Enabled and disabled the line several times to verify this, happened 100% of times.
