### ISSUE TITLE
Uploading truncates files

### ISSUE THREAD

**Issue by craigcabrey** [mkuf/prind#90]
This is quite a whacky issue I had to narrow down. For additional context, I am using the multiple printer custom compose file. Previously, I was using the standard setup with an Ender 3 S1 without any trouble (I haven't yet confirmed if the S1 instance is also experiencing this).
 
docker-compose.yaml (from prind 1.8.0):

```
[snip]
x-klipper-svc: &klipper-svc
  image: mkuf/klipper:latest
  restart: unless-stopped
  privileged: true
  volumes:
    - /dev:/dev
    - ./config:/opt/printer_data/config
    - run:/opt/printer_data/run
    - gcode:/opt/printer_data/gcodes
    - log:/opt/printer_data/logs

x-moonraker-svc: &moonraker-svc
  image: mkuf/moonraker:latest
  restart: unless-stopped
  volumes:
    - /dev/null:/opt/klipper/config/null
    - /dev/null:/opt/klipper/docs/null
    - ./config:/opt/printer_data/config
    - run:/opt/printer_data/run
    - gcode:/opt/printer_data/gcodes
    - log:/opt/printer_data/logs

x-ustreamer-svc: &ustreamer-svc
  image: mkuf/ustreamer:latest
  restart: unless-stopped
  command: --host=0.0.0.0 --port=8080 --slowdown --device=/dev/webcam --resolution=640x480 --format=MJPEG --desired-fps=30

## Service Definitions
services:

  ## Printer1
  ## Access api via port 8101/tcp and webcam via 8102/tcp
  slowboi-klipper:
    <<: *klipper-svc
    command: -I printer_data/run/slowboi.klipper.tty -a printer_data/run/slowboi.klipper.sock printer_data/config/slowboi.cfg -l printer_data/logs/slowboi.klippy.log
    labels:
      org.prind.service: klipper
      org.prind.printer: slowboi
  slowboi-moonraker:
    <<: *moonraker-svc
    command: -d printer_data -c printer_data/config/slowboi.moonraker.conf -l printer_data/logs/slowboi.moonraker.log
    ports:
      - 8101:7125
    labels:
      org.prind.service: moonraker
      org.prind.printer: slowboi
  slowboi-webcam:
    <<: *ustreamer-svc
    devices:
      - /dev/video0:/dev/webcam
    ports:
      - 8102:8080
    labels:
      org.prind.service: webcam
      org.prind.printer: slowboi

  ## Printer2
  ## Access api via port 8201/tcp and webcam via 8202/tcp
  hugeboi-klipper:
    <<: *klipper-svc
    command: -I printer_data/run/hugeboi.klipper.tty -a printer_data/run/hugeboi.klipper.sock printer_data/config/hugeboi.cfg -l printer_data/logs/hugeboi.klippy.log
    labels:
      org.prind.service: klipper
      org.prind.printer: hugeboi
  hugeboi-moonraker:
    <<: *moonraker-svc
    command: -d printer_data -c printer_data/config/hugeboi.moonraker.conf -l printer_data/logs/hugeboi.moonraker.log
    ports:
      - 8201:7125
    labels:
      org.prind.service: moonraker
      org.prind.printer: hugeboi

  ## Use Fluidd as Frontend
  fluidd:
    image: ghcr.io/fluidd-core/fluidd:latest
    restart: unless-stopped
    ports:
      - 80:80
    labels:
      org.prind.service: fluidd

volumes:
  run:
  gcode:
  log:
```

I uploaded a Calibration cube from PrusaSlicer (but also directly via Fluidd just to be sure) and the hash is different:

```
[craigcabrey@zephyrus Downloads]$ sha1sum xyzCalibration_cube_0.2mm.gcode 
6067b39f32f62ceb39c6b4fbe23d4fe8a2d22ef1  xyzCalibration_cube_0.2mm.gcode
```

```
root@klipper:/var/lib/docker/volumes/prind-180_gcode/_data/hugeboi/Calibration/PLA# sha1sum xyzCalibration_cube_0.2mm.gcode 
7761a530f74de2bd0433d544603849ccf3bf52d3  xyzCalibration_cube_0.2mm.gcode
```

It seems like roughly ~4k lines (not sure if there is a pattern here) went missing. I noticed this when my `END_PRINT` macro was nowhere to be found, but the pressure advance gcode I manually scp'd over did.

Any ideas welcome! For now, my workaround is to scp gcode over to my Pi but obviously I would much rather upload directly from within PrusaSlicer.
