### ISSUE TITLE
[Errno 13] Permission denied: '/dev/pts/1' -> 'printer_data/run/klipper.tty' RPI4

### ISSUE THREAD

**Issue by Seredar** [mkuf/prind#98]
docker-compose.yaml

```
services:
  klipper:
    image: mkuf/klipper:latest
    privileged: true
    volumes:
      - /dev:/dev
      - ./config/printer.cfg:/opt/printer_data/config/printer.cfg
      - ./run:/opt/printer_data/run
      - ./gcode:/opt/printer_data/gcodes

  moonraker:
    image: mkuf/moonraker:latest
    ports:
      - "7125:7125"
    volumes:
      - ./config/moonraker.conf:/opt/printer_data/config/moonraker.conf
      - ./run:/opt/printer_data/run
      - ./gcode:/opt/printer_data/gcodes

```
```
pi@mars:~ $ uname -a
Linux mars 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
pi@mars:~ $ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

pi-klipper-1    | Traceback (most recent call last):
pi-klipper-1    |   File "/opt/klipper/klippy/klippy.py", line 407, in <module>
pi-klipper-1    |     main()
pi-klipper-1    |   File "/opt/klipper/klippy/klippy.py", line 335, in main
pi-klipper-1    |     start_args['gcode_fd'] = util.create_pty(options.inputtty)
pi-klipper-1    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pi-klipper-1    |   File "/opt/klipper/klippy/util.py", line 42, in create_pty
pi-klipper-1    |     os.symlink(filename, ptyname)
pi-klipper-1    | PermissionError: [Errno 13] Permission denied: '/dev/pts/1' -> 'printer_data/run/klipper.tty'

any idea how to fix?
